services:
  gateway:
    image: gateway:0.0.1-SNAPSHOT
    ports:
      - "8080:8081"
    networks:
      - microservices-network

  resourceserver:
    image: resourceserver:0.0.1-SNAPSHOT
    networks:
      - microservices-network
      - SPRING_PROFILES_ACTIVE=docker
  auth:
    image: authservice:0.0.1-SNAPSHOT
    ports:
      - "9000:9000"

networks:
  microservices-network:
    driver: bridge