spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authservice:9000
          jwk-set-uri: http://authservice:9000/oauth2/jwks

  cloud:
    gateway:
      mvc:
        routes:
          - id: joke-route
            uri: http://jokeservice:8082/
            predicates:
              - Path=/api/jokes/**
            filters:
              - RewritePath=/api/jokes/?(?<segment>.*), /$\{segment}
          - id: quote-route
            uri: http://quoteservice:8083/
            predicates:
              - Path=/api/quotes/**
            filters:
              - RewritePath=/api/quotes/?(?<segment>.*), /$\{segment}