spring:
  application:
    name: gateway
gatew
  cloud:
    gateway:
      mvc:
        routes:
          - id: joke-route
            uri: http://jokeservice:8082/
            predicates:
              - Path=/api/jokes/**
            filters:
              - RewritePath=/api/jokes/?(?<segment>.*), /$\{segment}
          - id: quote-route
            uri: http://quoteservice:8083/
            predicates:
              - Path=/api/quotes/**
            filters:
              - RewritePath=/api/quotes/?(?<segment>.*), /$\{segment}
