spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: example-route
            uri: http://resourceserver:8080/
            predicates:
              - Path=/api/**
            filters:
              - RewritePath=/api/?(?<segment>.*), /$\{segment}
          - id: joke-route
            uri: http://jokeservice:8081/
            predicates:
              - Path=/jokes/**
            filters:
              - RewritePath=/jokes/?(?<segment>.*), /$\{segment}