spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authservice:9000
          jwk-set-uri: http://authservice:9000/oauth2/jwks

  cloud:
    gateway:
      mvc:
        routes:
          - id: joke-route
            uri: lb://jokeservice
            predicates:
              - Path=/api/jokes/**,/actuator/**
            filters:
              - RewritePath=/api/jokes/?(?<segment>.*), /$\{segment}
          - id: quote-route
            uri: lb://quoteservice
            predicates:
              - Path=/api/quotes/**,/actuator/**
            filters:
              - RewritePath=/api/quotes/?(?<segment>.*), /$\{segment}